### PR TITLE
Fix extra double-quotes when passing date to GET

### PR DESCRIPTION
**Pull request by spongessuck**
`JSON.stringify` on a date will add extra quotes around the string, so use `toISOString` instead if it's available.

### CODE REVIEW

**Comment by spongessuck** [comment]
Rebased from latest commits, ready to merge.

**Comment by troyanskiy** [comment]
Hello.
Thank you for your request.
I think it's not really good way to check date like that
```ts
if (value.toISOString)
```

I think it's better to check instanceof Date.
What do you think?

**Comment by spongessuck** [comment]
I had only made the change in the compiled javascript where `instanceof Date` didn't seem to work properly. It might work in Typescript- I'll try to get it to work unless you want to add it yourself.

**Comment by spongessuck** [comment]
I guess I didn't repack everything after my changes- changed it to `instanceof Date` and that seemed to do the trick.

**Comment by troyanskiy** [comment]
Thank you!

**Pull request merged**
