### PR TITLE
remove typescript files npm ignore

### PR DESCRIPTION
**Pull request by yamaha252**
the package is broken when npm installs it from another place (e.g. custom repository) If npm ignores typescript files

### CODE REVIEW

**Comment by troyanskiy** [comment]
That will provide regression on issue https://github.com/troyanskiy/ng2-resource-rest/issues/25 which was fixed with that pull request https://github.com/troyanskiy/ng2-resource-rest/pull/26

**Comment by troyanskiy** [comment]
I have published v 1.12.1
Please check change log.
To enable your way of mapping get params please set somewhere at app initialisation  `ResourceGlobalConfig.getParamsMappingType = TGetParamsMappingType.Bracket`

**Comment by yamaha252** [comment]
Thank you for your reply!
I think it's a little bit strange solution because when I install the package from any repository I have no main scripts at all.
I suggest using postinstall npm build and clean *.ts files by webpack or npm script.

**Comment by troyanskiy** [comment]
That strange. We have Nexus repository and we did not have that kind of problem.
I will check that later.

**Comment by yamaha252** [comment]
Thanks!
http://take.ms/lovdn

**Pull request closed without merging**
