### PR TITLE
Wrap data within a root node

### PR DESCRIPTION
**Pull request by jeremypele**
Hi!

As a lot of back-ends frameworks nowadays needs the resources sent to be wrapped within a root node, I just created this small PR to support this case.

I need to support this because I'm working with a Rails API.

Cheers!

### CODE REVIEW

**Comment by troyanskiy** [comment]
Hi @jeremypele !

Thanks for your PR. 
Could you please also update README.MD file?
If you can't do that, I will do it later...

**Comment by jeremypele** [comment]
@troyanskiy Just pushed a modification on README.MD. Just tell me if there is anything else I need to do :)

**Comment by troyanskiy** [comment]
Great! Thanks!

**Comment by troyanskiy** [comment]
I've just published v 1.10.0 to NPM.
Thanks for the PR again!

**Pull request merged**
